### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/StreamDeck-AudioMute#1]
Probably a useful starting point: https://developer.apple.com/library/archive/technotes/tn2223/_index.html

**Comment by ccharlton** [comment]
+1

**Comment by fredemmott** [comment]
*very* early, nowhere near useful. All I have for now is a terminal executable that does this:

```
fred@Freds-MBP build % ./Sources/audiodevices_test
Default ID: 48 48
Muted? false. Muting...
Muted? true... sleep(3)
Muted? false
```

... and spotify goes silent for 3 seconds in the middle

**Comment by fredemmott** [comment]
Open questions:
- how to update the plugin if you hit the mute key on your keyboard or mute from control panel
- how to update the plugin if you have the button set to be 'default device' and the default changes
- how to update the plugin if you disconnect the selected device

All of these are probably AudioObjectAddPropertyListener -  matter of figuring out how that works.

Also:
- what if you configure the plugin to use a specific device, but it's not connected when the streamdeck software starts, e.g. usb or bluetooth headphones? On Windows, it's possible to retrieve a list of *all* known audio devices, not just present ones, but I'm not seeing that in coreaudio for macos

**Comment by fredemmott** [comment]
<img width="952" alt="Screen Shot 2020-06-28 at 8 16 20 PM" src="https://user-images.githubusercontent.com/360927/85969384-54eb2000-b97c-11ea-9f31-ca05e8661494.png">

The basics work, but it's super easy to break. 

> how to update the plugin if you hit the mute key on your keyboard or mute from control panel

This one is done :)

**Comment by fredemmott** [comment]
Here's a preview; several known bugs when devices are removed (e.g. bluetooth/usb sound cards/headphones)

[com.fredemmott.micmutetoggle.streamDeckPlugin.zip](https://github.com/fredemmott/StreamDeck-AudioMute/files/4900398/com.fredemmott.micmutetoggle.streamDeckPlugin.zip)

**Comment by rtgoodwin** [comment]
FWIW Toggle Mute works like a champ for me on Big Sur, using Specific device (a USB mic). Standard (the same mic selected as Default in Sound) does not. Thanks! :)
