### ISSUE TITLE
[Feature Suggestion] Automute at Startup

### ISSUE THREAD

**Issue by thowtue** [fredemmott/StreamDeck-AudioMute#10]
hello,
I'd like to know if it's possible to add an option to automute the specified device on StreamDeck startup ?
Because i'd like to automute the mic at windows startup and don't really know how to do that !

Thank you :)

**Comment by fredemmott** [comment]
Sorry, I don't think this would be a good fit for Streamdeck: generally, I don't think launching the streamdeck software should change anything about your system except that now you have buttons that do things.

Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.
