### ISSUE TITLE
vcruntime140_1.dll was not found

### ISSUE THREAD

**Issue by jmanny14** [fredemmott/StreamDeck-AudioMute#12]
It seems that the latest version of Audio mute v2.3 broke the plugin. 
I received an error message that vcruntime140_1.dll was not found and the action no longer works on my StreamDeck. 
I am running  the latest version of streamdeck 4.7.0.12981 and the latest firmware 1.02.005

**Comment by fredemmott** [comment]
What version of windows are you using?

Please follow the instructions at https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running

I'm looking for a version like  "Windows 10 version 1909, build 18363.900", not just "Windows  10"

**Comment by fredemmott** [comment]
Installing the latest package from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads should solve this; will look into including them in the next version

**Comment by jmanny14** [comment]
Fred,
I am using Windows 10 Pro version 1909 build 18363.476
Thanks for the quick response

-------- Original Message --------

**Comment by TwinProduction** [comment]
FYI, I stumbled on the same issue this morning, and as @fredemmott suggested, my issue was resolved.

The system in which this issue happened is the following:
Windows 10 Pro version 2004 build 19041.329

**Comment by fredemmott** [comment]
This should be fixed by [v2.4](https://github.com/fredemmott/StreamDeck-AudioMute/releases/latest)

**Comment by jmanny14** [comment]
Downloading the latest Visual C package did indeed work for me. Thank you

**Comment by fredemmott** [comment]
Thanks; that should be unneeded with v2.4
