### ISSUE TITLE
Mic is permanently muted

### ISSUE THREAD

**Issue by DerSoftwerker** [fredemmott/StreamDeck-AudioMute#13]
Hey there, 

I have the streamdeck to mute my mic for streams as well as during the day for occasional calls during work. 

Today I updated the streamdeck software, while the mic was muted. 
After a restart, streamdeck would not fully load, another restart later the mic mute button was showing the mic active but it is still muted. 

Toggling the Button does not unmute it anymore. The mic is active in the system but it is simply not recording. It does work by pluggin it into a different USB slot, which then creates a different audio device.

The USB port works just fine with my headset now. 

The Plugin has permanently muted this specific Audio device and even after deleting the device and plugin the microphone again, as the device is newly installed with the same name, it is muted again.

I have no option to enable this specific audio device again.

**Comment by DerSoftwerker** [comment]
I am not entirely sure how your plugin did mute the Microphone btw. 

The system just shows it as working normally, just not recieving any sound.

**Comment by fredemmott** [comment]
What version of windows are you using?

If you open the device  in sound control panel (In windows 10 sound settings), open the levels tab.

There’s a mute/unmute button there - that’s what it changes.

**Comment by fredemmott** [comment]
Also, what’s your streamdeck software version?

**Comment by DerSoftwerker** [comment]
Greetings and thanks for the fast reply.

System is Windows 10 Pro, Updated to the latest Version.
The mute/unmute Button is there but the streamdeck des not change it for the broken sound device. Muting/Unmuting/Setting Level to 0 and back to 100 does not change anything.

All of that works fine with the other audio device that was created after pluging in the mic into a different USB Port.

**Comment by fredemmott** [comment]
Just checking: the window you were looking at looks like this:

![589999EA-B5B8-40C6-B38A-12BFAE6C4941](https://user-images.githubusercontent.com/360927/85469630-c5e89d00-b562-11ea-8d5a-490c27b1cd39.png)

... and you’re clicking on those speaker icons on the right hand side?

If it looks like the next picture, it’s the wrong page:

![089276F2-06A0-4FCA-8602-FEEAE72CC6E3](https://user-images.githubusercontent.com/360927/85469819-00ead080-b563-11ea-8e7e-d6e926e85eb8.jpeg)

**Comment by DerSoftwerker** [comment]
Correct, thats the settings I am looking at. The Mute Button is not active, level at 82. I can manually mute or unmute without any change. Pressing the Button on the streamdeck changes the display icon ont he streamdeck - but does nothing else.

**Comment by DerSoftwerker** [comment]
Yes, I double checked that I have the correct sound device in the streamdeck software selected.

**Comment by fredemmott** [comment]
Sorry, just to be clear: when you click the mute/unmute thing in the levels tab:

- does it actually mute/unmute the microphone?
  - if not, does it work if you fully quit the streamdeck software first?
- does it update the streamdeck? (I’m seeing no, just trying to be very clear)

**Comment by DerSoftwerker** [comment]
No stress, this is a unique issue as it seems.

The levels Button did mute/unmute for sure about 30h ago. I updated Streamdeck to 4.7.0.12981 about 4 hours ago, the mute was active at that time. About 3h ago I did start my stream and noticed that the mic does not record any sound. No other System or driver updates in between.

Currently, clicking the button next to the levels bar manually changes the symbol, but the mic remains muted. Pressing the button on the streamdeck does not change the symbol next the level bar.

Closing the Streamdeck Software does not change the outcome. It feels like the mic has been muted in a way, that the system does not recognize it. And the AudioMute plugin is not able to revert it.

**Comment by fredemmott** [comment]
Sorry, you need to reach out to your sound card manufacturer - that’s a driver bug.

If they’re willing to take details, mute was set with https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudioendpointvolume-setmute

**Comment by fredemmott** [comment]
Does rebooting fix it?

I’m wondering if it thinks something is using it exclusively, and a reboot would reset that

**Comment by DerSoftwerker** [comment]
Found a solution if anybody else runs into this. 

In the Windows 10 Settings below the Mic Volume bar, the troubleshoot button actually identified the sound device being muted. It solved it and after a restart, the mic was working again. Notably, I shutdown the PC with the the mic not muted in Streamdeck and when starting up, it came online with the muted symbol. 

As I suspected, somehow the device was muted without event the system noticing it. Luckily the automatic Troubleshooting did fix it. (I tried the classic automated troubleshooting for audio devices earlier, this one did not work.)

(Restarts did not help, was the first thing I tried. I even did unplug, deinstalled the device via device manage, restarted, pluged back in without results.)

**Comment by fredemmott** [comment]
@DerSoftwerker if you don’t mind, what’s the make/model of the usb audio device?

**Comment by DerSoftwerker** [comment]
Its an Auna Nic CM 900 - a simple USB microphone. Standard Windows drivers, no fancy extra software needed.

**Comment by fredemmott** [comment]
I'm closing this; this is not saying "there's no issue here", but there's no way to investigate this at present. Will re-open if that changes.

**Comment by fredemmott** [comment]
This might be #23
