### ISSUE TITLE
fails to install on streamdeck 4.8

### ISSUE THREAD

**Issue by seanmcne** [fredemmott/StreamDeck-AudioMute#14]
Hi I noticed the mic mute action on my streamdeck get disabled the other day 
Now when trying to install, it downloads but then never gets installed - are you already aware of this problem? 

![image](https://user-images.githubusercontent.com/2292260/87093465-dbb4be00-c202-11ea-97c1-7bf8ec502703.png)

![image](https://user-images.githubusercontent.com/2292260/87093474-e0797200-c202-11ea-9e9a-77c2f9422995.png)

![image](https://user-images.githubusercontent.com/2292260/87093465-dbb4be00-c202-11ea-97c1-7bf8ec502703.png)

![image](https://user-images.githubusercontent.com/2292260/87093509-ecfdca80-c202-11ea-9d53-a2c0a854e2a9.png)

the logs are, unfortunately, not super helpful: 

16:39:30.567                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates
16:40:15.511                     StreamDeck                        ESDPluginManager::InstallPlugin():              Failed to install plugin from 'C:\Users\\AppData\Local\Temp\Stream Deck-pQbdOk\com.fredemmott.micmutetoggle.sdPlugin' to 'C:\Users\\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.micmutetoggle.sdPlugin'
16:40:23.095                     StreamDeck                        ESDPluginManager::InstallPlugin():              Failed to install plugin from 'C:\Users\\AppData\Local\Temp\Stream Deck-iHSNyX\com.fredemmott.micmutetoggle.sdPlugin' to 'C:\Users\\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.micmutetoggle.sdPlugin'
16:40:46.164                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
16:40:46.175                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates

**Comment by fredemmott** [comment]
- does this also happen if you install from https://github.com/fredemmott/StreamDeck-AudioMute/releases ?
- Are you using antivirus? Can you check if it got confused by the plugin and deleted it?
- `C:\Users\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.micmutetoggle.sdPlugin`:
   - is there a .exe file in there? It might be `C:\Users\YourUsername\AppData` instead of just C:\Users\AppData
   - if so, what happens when you try to run it?

**Comment by seanmcne** [comment]
Thanks for the response, I went into %appdata%\Elgato\StreamDeck\Plugins\com.fredemmott.micmutetoggle.sdPlugin and I just deleted the com.fredemmott.micmutetoggle.sdPlugin folder entirely. Once i did that, then I was able to re-install the plugin and it's working now again. 

Thanks!
