### ISSUE TITLE
Issues using GIFs in the icon image

### ISSUE THREAD

**Issue by Final71** [fredemmott/StreamDeck-AudioMute#15]
I'm using a RGB Profile for all of my buttons on my streamdeck, similar to this video:

https://www.youtube.com/watch?v=lEqjSizn46U

I've found that when I create my custom icon for the Microphone state using a GIF like you see above, it will usually lose sync with the other rows of icons after a few seconds of use.  Even after refreshing the streamdecks icons the issue will almost instantly reoccur.  I've found that using other button types like a multiaction will not exhibit that same reaction.  

Is there anything on my end I could do to maintain the integrity of the GIF?  I've attached the GIFs I am using as reference

Thanks!  Love your work!
![Mic-Off](https://user-images.githubusercontent.com/17991844/90940060-5fe19000-e3c2-11ea-8c7b-c70d4f851ee6.gif)
![Mic-On](https://user-images.githubusercontent.com/17991844/90940063-6112bd00-e3c2-11ea-8135-efb4617b2722.gif)

**Comment by fredemmott** [comment]
Sorry for the extremely slow reply; in short, setting the state resets the gif. I could probably fix this issue for when the streamdeck is first launched, but will get out of sync the first time you press the button, and I don't think that's avoidable. I'd be interested in a pull request to improve this, but given the limitations, I'm unlikely to spend time on this.

**Comment by Final71** [comment]
No worries at all, That is totally understandable and given how it functions, probably not worth the development time for it.  I dont think Im skilled enough to debug and resolve this so Ive mostly just given up to the gif idea at the moment.  Appreciate you getting back to me on this topic though, thank you!

**Comment by fredemmott** [comment]
I'm going to close this as it seems unlikely it will be done; if someone is interested in doing this, I'd be happy to review pull requests.
