### ISSUE TITLE
plugin stream deck self-mute / deaf discord

### ISSUE THREAD

**Issue by adrianofbcordeiro** [fredemmott/StreamDeck-AudioMute#16]
how do i uninstall com.fredemmott.discord from my desktop, why is it not working, lap to install it does not appear on the side, and says it is already installed!

**Comment by fredemmott** [comment]
- open 'more actions' in the bottom right of the streamdeck software, find the plugin, and click uninstall
- if you have further issues that are specific to using the discord plugin, file it at https://github.com/fredemmott/streamdeck-discord
- if you have general issues with how to install or uninstall plugins, please contact elgato support
