### ISSUE TITLE
[Feature Request] Add ability to enable/disable audio device in Windows

### ISSUE THREAD

**Issue by HunterAP23** [fredemmott/StreamDeck-AudioMute#17]
Was wondering if it would be possible to outright enable and/or disable an audio device (playback or recording) directly, rather than muting it.

I know it's a strange ask, but at least in my situation I need to disable then re-enable some audio devices, usually when I disconnect my audio gear from my main PC to use on my work PC, and then reconnect them on my main PC.

**Comment by fredemmott** [comment]
I ended up poking around with disabling/enabling devices for an unrelated project; in theory this is possible via the `SetupDi` family of functions, however these require that the program be running as administrator. Closing as I don't want to make that a requirement for this project, or encourage it.
