### ISSUE TITLE
Mute mic in windows

### ISSUE THREAD

**Issue by AgraveiNstream** [fredemmott/StreamDeck-AudioMute#19]
When im using this pluggin im muting mic in OBS/Discord but not in windows. All the time my interface "collects the voice of the environment" even if muted on Stream Deck. Am i doing somethink wrong? I want to switch off my mic after work by one click on stream deck. Using this plug its impossible for me :/ thx for help

**Comment by fredemmott** [comment]
This plugin only controls windows mute; it has no way of affecting OBS or Discord except via the windows settings - those being muted shows this plugin is working and changing the windows setting.

is it possible you have multiple input devices active and another one is interfering?

**Comment by fredemmott** [comment]
This might be the same as #23
