### ISSUE TITLE
Request: Audio Input/Output Device Switching

### ISSUE THREAD

**Issue by ripnet** [fredemmott/StreamDeck-AudioMute#21]
Love your work!

On my mac, I frequently need to change the input and output audio device. Is it possible to have your software control this? I would love to enumerate my devices as buttons and be able to select which device is input or output.

**Comment by fredemmott** [comment]
A different plugin does this - https://github.com/fredemmott/StreamDeck-AudioSwitcher/issues/18 has a version with some Mac support linked in the comments
