### ISSUE TITLE
Mute Changing Mic Volume

### ISSUE THREAD

**Issue by cornwolf** [fredemmott/StreamDeck-AudioMute#26]
Hi 

I am new to stream deck only had one for the last couple of months but been using your mute since I got it. Since the latest update via Stream Deck when I mute the mic every now and again it changes the Volume/Gain of the mic down to around 2 rather as well as muting the mic. When I unmute no one can hear me and I have to go into settings and turn it back up. 

I hope this makes sense.

**Comment by fredemmott** [comment]
There is no change to how the plugin mutes/unmutes: it asks the operating system to do this explicitly, and does not use a volume setting. This is almost certainly a bad driver/software update or issue with windows, along the same lines as  https://github.com/fredemmott/StreamDeck-AudioMute/discussions/23 - or some other software on your computer having a bad interaction with the system mute control(e.g automatic gain control in some VC software?)

This is unlikely to be a bug (or fixable) here - however you might want to try:
- making a note of any particular applications you’re using or activities you’re doing when this happens
- If you restore the volume, mute again then unmute again immediately, does the same thing happen?
- if you find a way to make it happen reliably, does the same thing happen if you do win-r, type “mmsys.cpl”, find your device, and mute/unmute from the “levels” tab? This would entirely rule out the plugin

also, are you running any vendor software for your microphone?
