### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by AceofCookies** [fredemmott/StreamDeck-AudioMute#29]
Hello!

I don't currently see a way to switch both communications device and default device at the same time, consequently it works perfectly in for example discord and OBS, which uses default communications device , but will not work for Viber calling.

Thanks!

**Comment by fredemmott** [comment]
You seem to have filed an issue in the wrong place - this is for the mute plugin, not switcher plugin. That said, I won’t be adding it: there isn’t a clear correct behavior if only changing one works.

you probably want to use the “set audio device” action with the multi action switch feature

**Comment by AceofCookies** [comment]
Sorry I didn't quite understand your response. Would you be against adding an option to change both roles at the same time, rather than changing just one?

![image](https://user-images.githubusercontent.com/46501822/119857531-f293fa00-bf13-11eb-9527-3f620fab4a88.png)
