### ISSUE TITLE
Mic Mute not working

### ISSUE THREAD

**Issue by Nyiax** [fredemmott/StreamDeck-AudioMute#30]
I am using a HyperX 7.1 USB headset/mic and the StreamDeck Mute function does not mute the microphone. I have used other mic mute functions for Discord and Twitch, muting the headphone _output_, and those work fine, but trying to mute the mic at the Windows level is not functioning. Screenshot attached to show when Mute toggle is activated, both Twitch and Windows is capturing sound from the only mic I have. Anything I can do to troubleshoot further? Thanks in advance for your help. 

![image](https://user-images.githubusercontent.com/19877560/118167076-81b4f400-b3e3-11eb-99ca-bc86ffdeeecd.png)

**Comment by fredemmott** [comment]
> trying to mute the mic at the Windows level is not functioning

Sorry, but unless you have something else running that takes over the volume control (check your system tray, but other than that, you'd be aware of this), there's nothing the plugin can do. This sounds like another case of #23 :(
