### ISSUE TITLE
Can't mute usb audio Interface

### ISSUE THREAD

**Issue by jfgosselin** [fredemmott/StreamDeck-AudioMute#31]
Hi,

I can't mute my Motus M4 Audio interface or Behringer UMC22 .  It does work with the MacBook mic.

- StreamDeck-AudioMute v3.1.0
- StreamDeck 4.9.4
- macOS Big sur 11.3.1
- MacBook Pro (Intel)

        M4:

          Default Input Device: Yes
          Input Channels: 8
          Manufacturer: MOTU, Inc
          Output Channels: 4
          Current SampleRate: 44100
          Transport: USB
          Input Source: Default
          Output Source: Default

        USB Audio CODEC (UMC22):

          Input Channels: 2
          Manufacturer: Burr-Brown from TI
          Current SampleRate: 48000
          Transport: USB
          Input Source: Default

**Comment by fredemmott** [comment]
> Motus M4 Audio interface or Behringer UMC22

Many professional devices do not have hardware support for mute (at least in a way that MacOS understands), and MacOS is unable to mute them - so the plugin can't either. I don't have either of the devices you mentioned though so can't confirm this is the case.

Are you able to mute them with the keyboard mute/volume keys when they're the active device, or from audio midi settings?
