### ISSUE TITLE
macOS Monterey breaks input only mute

### ISSUE THREAD

**Issue by Houston-Synex** [fredemmott/StreamDeck-AudioMute#43]
Post upgrade to macOS 12.0.1 (21A559) using this plugin mutes audio output and input no matter the configuration.

Steps to reproduce:
1) add plugin to Stream Deck
2) configure Device to be: 'Default Input' OR _any_ 'Specific Input Device'
3) pressing the corresponding button the on stream deck results in audio output being muted

System information:
macOS 12.0.1 (21A559)
Stream Deck 5.1.3 (14750) FQ 3.00.000
Audio Mute V3.0.1

**Comment by florianeckerstorfer** [comment]
@Houston-Synex Looks like this is a bug in Mac OS Monterey. For me it doesn't matter where I mute myself with a bluetooth device connected, it always also mutes the audio input. Even when I slide the input volume in the Sound preference pain to 0, it mutes my output. https://apple.stackexchange.com/questions/430038/macos-monterey-bluetooth-mic-issues-when-mute-adjust-input-volume

**Comment by fredemmott** [comment]
If might be useful to check with the 'audio midi setup' app included with macos; if that's not capable of doing the changes you want, it's likely impossible for this plugin (or any other) to until/unless a MacOS update changes it.

**Comment by Houston-Synex** [comment]
@fredemmott 
Thank you for the information

Confirmed that muting 'input' also mute 'output' when using a bluetooth device on macOS 12.0.1
![Screen Shot 2021-12-02 at 11 05 30 AM](https://user-images.githubusercontent.com/88859551/144458843-d49fe534-b8fa-4ad7-bb56-61db10d4348b.png)

My understanding is that therefore this a mac os issue - do you want to close this ticket?
