### ISSUE TITLE
Option to toggle mute on all inputs

### ISSUE THREAD

**Issue by calebcbaker** [fredemmott/StreamDeck-AudioMute#46]
Enhancement: 

What would really take this to the next level for me is the option to toggle mute on all input devices. Sometimes using Teams or Skype I may switch what audio device i'm using within that app which breaks the AudioMute functionality because it's either is stuck muting the default system input, or some other device that it was configured to implicitly mute.

**Comment by fredemmott** [comment]
Sorry, I generally don't want multi-device things in here:
- it's not clear what it should show - or what pressing it should do - if some devices are muted and some are unmuted
- it's doable with Elgato's existing features, via a [multi-action switch](https://www.reddit.com/r/ElgatoGaming/comments/dvdg6b/stream_deck_update_44_multi_action_switch_random/), which has clearer meaning than a standalone button as it's not expected to reflect current state

**Comment by timtucker** [comment]
I would really like to see this as well and had a few thoughts on the issues raised:

**it's not clear what it should show - or what pressing it should do - if some devices are muted and some are unmuted**

Window's Power Toy's global mute already does this and has a very reasonable approach:
- If the chosen mic is set to "All", the toggle is not considered to be in the "off" state unless all mics are muted
- When toggling back to "on", all mics are turned on (regardless of what their state was before toggling "off")

https://docs.microsoft.com/en-us/windows/powertoys/video-conference-mute

They also have the full source available for their implementation under MIT license:
https://github.com/microsoft/PowerToys


**it's doable with Elgato's existing features, via a [multi-action switch](https://www.reddit.com/r/ElgatoGaming/comments/dvdg6b/stream_deck_update_44_multi_action_switch_random/), which has clearer meaning than a standalone button as it's not expected to reflect current state**

Using a multi-action switch can be cumbersome to maintain and requires you to go in and add a new action every time you add a new mic.

With a global option it's "set and forget" -- no matter what you may add to the system tomorrow you only need to configure the button once.

I have at least 8 different input devices at the moment from trying out different Bluetooth headsets -- even for the one that I eventually settled on, they were cheap enough that I have 3 that I rotate between whenever battery gets low.

I don't really care which is plugged in at the moment, when I want to mute I just want to mute everything.
