### ISSUE TITLE
Audio Mute Toggling Both Interfaces on MacOS Monterey

### ISSUE THREAD

**Issue by hijewpositive** [fredemmott/StreamDeck-AudioMute#47]
Regardless if I choose Input or Output as the source, toggling Mute mutes both interfaces. This was not an issue on MacOS Big Sur. Only began after I updated.

**Comment by fredemmott** [comment]
Sorry, this appears to be a bug/change in MacOS itself - see #43

**Comment by hijewpositive** [comment]
Ah sorry, thanks for the quick reply!!
