### ISSUE TITLE
Mic stuck on mute after using

### ISSUE THREAD

**Issue by mmeehan07** [fredemmott/StreamDeck-AudioMute#52]
### Discussed in https://github.com/fredemmott/StreamDeck-AudioMute/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **mmeehan07** January 12, 2022</sup>
Has anyone else had this issue?  I cannot get any microphone off mute on my macbook pro after using the plugin.  I try to unmute in both system preferences and audio midi setup, and it automatically continues to move it back to mute.  Any ideas?</div>

**Comment by fredemmott** [comment]
Not a general issue; the support discussion is the right place for your questions.
