### ISSUE TITLE
Yellow Exclamation Icon? Started Happening Recently

### ISSUE THREAD

**Issue by coolspot18** [fredemmott/StreamDeck-AudioMute#54]
Hello,

The audio mute plug-in suddenly stopped working and is returning a yellow exclamation icon.

The plugin is also not returning ANY settings - the configuration page is completely blank. 

Any idea why that could happen?

Are there any logs I can check to see why the plugin is unable to control my microphone?

I'm running 3.0.1 plugin and Stream Deck software 5.1.4.14753, Windows 10.

UPDATE: I rebooted the PC and the configuration page now shows up... but why would it suddenly stop working?

UPDATE 2: Plugin is dead again.... It's very unreliable all of a sudden.

**Comment by andyt-f** [comment]
I have the same problem which I thought was related to the StreamDeck 5.2 software - but probably isn't having seen the original post.

I also got the yellow exclamation icon. I decided to uninstall and reinstall the plug in - big mistake! The plug in says that it has installed but actually doesn't. When I exit the plug in library and return, the plug in is available for installation again.

**Comment by coolspot18** [comment]
I just installed Stream Deck 5.2 and the issue persists. I uninstalled the plug-in completely, ensured that com.fredemmott.micmutetoggle.sdPlugin is deleted in the plugin folders, reinstalled, and how it's working again ... but for how long.

I'm not sure why certain icons have trouble being loaded/run in Stream Deck?

**Comment by andyt-f** [comment]
Your post got me thinking. I have a StreamDeck on another PC so I installed AudioMute on that. I then found com.fredemmott.micmutetoggle.sdPlugin (in C:\Users\[user name]\AppData\Roaming\Elgato\StreamDeck\Plugins), copied and pasted it to the PC with the issue, quit the software and restarted and all ok. 

I then installed v5.2 of StreamDeck and it's still OK. The plugin also shows as being installed in the StreamDeck Store.

I don't know what is preventing it from installing from the store but I have Audio Mute back so I'm happy!

**Comment by coolspot18** [comment]
It stopped working for me this morning again - I restarted the Stream Deck software multiple times and it still would not work.

I had to unplug the Stream Deck completely for functionality to work again.

I noticed certain plugins always have trouble loading, specifically Audio Mute and other plugins from Bar Rader (Advanced Launcher).

**Comment by shigeya** [comment]
Zoom extension also has a similar problem. The same alert icon appears on pressing the button. Uninstalling and Installing fix the issue. Thanks for the workaround.

**Comment by fredemmott** [comment]
I've added https://github.com/fredemmott/StreamDeck-AudioMute/blob/master/TROUBLESHOOTING.md with some of the common causes of this addressed
