### ISSUE TITLE
Plugin causes windows to ignore mic settings after restart if set to mute.

### ISSUE THREAD

**Issue by Mitsuma** [fredemmott/StreamDeck-AudioMute#6]
I'm experiencing a rather odd issue with the plugin.
After thinking it might be something else I found out that it seems to be the Mic Mute itself.
The issue is that after a restart the mic is permanently active and ignores any Windows volume or mute settings. Only another full restart fixes this.

To reproduce (at least on my machine) you do the following:
Mute the mic via the stream deck the the plugin.
Shutdown the PC.
Start the PC.
The Mic is now always active and ignores any inputs.
(The streamdeck still shows it muted as does the windows setting.)

What I mean by "ignores windows settings" is best shown by this recording:
https://gfycat.com/nippyuglygiantschnauzer
In there I tap my microphone (video has no audio), you can see it light up in two of the windows settings, it still records sounds which I can playback to my headset to confirm.
Now you can also see me mute the mic or set the volume to 0, both settings are ignored. 

Should be noted that the plugin still "works", at least as far as doing the action of muting (icons change, windows sets it to mute) but since it somehow causes the mic to be permanently active it does not actually get muted.

System: Windows 10 64bit
Version of Plugin: 1.1
Streamdeck Mini firmware v2.03
Streamdeck Software v4.1.0.9958
Soundcard: Soundblaster Z (Mic connected via 3.5mm)

**Comment by Mitsuma** [comment]
Just as I finished writing this I noticed there is a 2.0 here on the github.
I will see if that might fix the issue somehow.

**Comment by Mitsuma** [comment]
In a quick test I could not reproduce the issue anymore, the mic stays muted fine through a restart.
I leave this open for now, not sure if have an idea what the issue was, maybe you got an idea what it was.

**Comment by Mitsuma** [comment]
Actually it seems like i have to take that back. The issue appeared again.
Didn't do anything special, started my PC basically and went to make some food, locked PC and came back to mic being on despite it set to mute again.

**Comment by Mitsuma** [comment]
As a last update, I could fully confirm that its the plugin. Since a closing of the sdmicmute.exe via the task manager fixes the issue. The plugin naturally restarts again by the streamdeck, so it works fine after killing the process.

**Comment by fredemmott** [comment]
This is a pretty serious driver or hardware bug: if any application is able to receive audio from a microphone that's muted, it's a driver/hardware/windows bug, regardless of what specific application triggers it.

That said, it might be #9 triggering this, keeping one of the /output/ devices open - you can find out if that's the case by seeing if disabling feedback sounds fixes the problem. If so, it's still a driver bug, but this plugin will stop triggering it in the next release.

This plugin does 4 things with audio devices:
- fetches a list of them
- toggles mute
- asks windows to tell it when the volume is changed
- plays feedback sounds if that's ticked

None of these should cause this.

I'm unable to reproduce this, though I don't have a soundblaster; if the next release doesn't fix this, you probably want to follow up with your soundcard manufacturer. This being possible with their drivers is a privacy issue.
