### ISSUE TITLE
On MacOS, muting mic also mute output sound device

### ISSUE THREAD

**Issue by idefxH** [fredemmott/StreamDeck-AudioMute#60]
Hello, on Mac OS X, when I try to mute my mic while using my headphone as output device, they both get muted.

Doesn't happen when I mute my mic while using the default speaker of my system.

Could be related to the fact both output and input devices share the same name on my headphones.

**Comment by fredemmott** [comment]
Sorry; this uses Apple's only documented way to request that the device only be muted for input or output, but it's up to Apple or possibly the device manufacturer to fix that if it isn't working.
