### ISSUE TITLE
[Feature Request] Show current volume on button title when unmuted

### ISSUE THREAD

**Issue by Nillinn** [fredemmott/StreamDeck-AudioMute#64]
Like the example below, maybe this plugin could use the button's title bar to show the OS's current volume on the button while in the unmuted state.

The image references below were taken from the Win Tools stream deck plugin:

![image](https://user-images.githubusercontent.com/94562218/189500332-0f26ab13-dc61-4541-b75b-d1ee84f33a88.png)
![image](https://user-images.githubusercontent.com/94562218/189500343-0ecb374b-1e2d-428a-983d-27fc4491a979.png)

**Comment by karlbecker** [comment]
By volume, do you mean the level of the input volume?

This sounds similar to the idea I put in - https://github.com/fredemmott/StreamDeck-AudioMute/discussions/65 - except there I'd like to see how loud or not the sound is that the microphone is picking up.

**Comment by fredemmott** [comment]
Sorry, closing this: realistically, I'm not going to do anything that involves changing the image:
- for stuff in C++, it's either a fairly heavy additional dependency, or it needs separately implementing for MacOS and Windows
- the streamdeck software doesn't support htis kind of thing well: it breaks the built-in image selection.
