### ISSUE TITLE
[Feature Request] Push-to-Mute

### ISSUE THREAD

**Issue by Gummientchen** [fredemmott/StreamDeck-AudioMute#66]
Hi,

It would be great to have a push-to-mute functionality for the Stream Deck Pedal. The microphone would be muted when the Stream Deck Pedal button is held down and unmuted when the button isn't pressed any more.

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/227722233-8d96cf37-a997-4ff8-804c-a37a26139d24.png)

This is already there - the PTT option acts as PTM if the device is unmuted.
