### ISSUE TITLE
Mute on Mac not working for output device

### ISSUE THREAD

**Issue by SemperFi89** [fredemmott/StreamDeck-AudioMute#71]
I have the Toggle Mute button setup on my Stream Deck XL on a MacBook Pro, and when I change the device to any of my output devices, it flashes a yellow warning sign on the stream deck icon and it doesn't work.

![Mac Info](https://github.com/fredemmott/StreamDeck-AudioMute/assets/98057782/c27b6123-50d0-4f46-a2d1-69e4fb4bdbbc)

**Comment by fredemmott** [comment]
Mute on MacOS requires hardware support. This is a limitation of your device or driver.
