### ISSUE TITLE
Audio Mute issue on Elgato Stream Deck Mini, not working at all, installed but not installed

### ISSUE THREAD

**Issue by Mei69** [fredemmott/StreamDeck-AudioMute#72]
Hi there, 

Im having an issue with the Audio Mute plug-in on Elgato Stream Deck Mini.

When i click on Install, it shows it is stalling and installed.
However it is not showing on the list of app on the left on Stream Deck app.
Also the button to Uninstall is not working, when i close the Store window and re-enter, the Audio Mute is showing again with blue icon to Install. Do not rly know why is that happening.
The device is new. I tried 2 times already to remove the Elgato Stream Deck software and get it resinstalled from scratch.
However every time i do that, the Stream Deck seems to have some internal memory and all setting are coming back and same issue with Audio Mute plug-in occures.

This issue only occure with Audit Mute plug-in, every other plug-in is working and can be re-installed with no issues.

Please advice if that can be solved somehow. Is that a software or a hardware issue rather?

Btw: Windows 10 user, not sure if its important.

Thanks for help!

Wiktor

**Comment by fredemmott** [comment]
Sorry, installation is entirely out of my control - you need to contact elgato support.

**Comment by Mei69** [comment]
Ok, will do thanks.
But whats also weird is that even when its shows that the plug-in is not installed, when in try do install it from your page 
https://github.com/fredemmott/StreamDeck-AudioMute/releases
[com.fredemmott.micmutetoggle.streamDeckPlugin](https://github.com/fredemmott/StreamDeck-AudioMute/releases/download/v3.1.0/com.fredemmott.micmutetoggle.streamDeckPlugin)

It shows pop-up screen info that it is already installed.
