### ISSUE TITLE
Bug: Can't mute monitor speakers on macOS Sonoma

### ISSUE THREAD

**Issue by Coder84619** [fredemmott/StreamDeck-AudioMute#77]
On macOS Sonoma I can adjust the output volume of my Dell monitor speakers (connected via DisplayPort) with your plugin, but the toggle mute does NOT work.

**Comment by fredemmott** [comment]
macOS does not support mute on devices without hardware support; software like https://rogueamoeba.com/loopback/ can be used to create a virtual device with support

**Comment by Coder84619** [comment]
LOL I'm not spending $99 for mute functionality.
