### ISSUE TITLE
Expose fuzzy match option

### ISSUE THREAD

**Issue by Matt-17** [fredemmott/StreamDeck-AudioMute#78]
I like this addon and is probably my most used. But unfortunately I have sometimes issues - probably after a restart - that it's not remembering the correct device. I click the button and nothing happens - even points out, it's not existent. Then I have to go to dashboard and choose "another" mic, that has the same name and it's working again. Don't know why this happens and is pretty rarely, but maybe somebody could check this and add a fallback behavior.

**Comment by Matt-17** [comment]
I thought about this, that it's not usual behavior. I have an 10 years old "3- LD Systems". Maybe I should look out for a new one.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-AudioMute/releases/tag/v3.3.0-beta1
