### ISSUE TITLE
Mic Mute semi-broken after last Stream Deck update

### ISSUE THREAD

**Issue by grimsi** [fredemmott/StreamDeck-AudioMute#8]
There is already a similiar issue open on the repo of your other plugin but I wanted to make you aware that this issue also exists with the Audio Mute plugin.
https://github.com/fredemmott/StreamDeck-AudioSwitcher/issues/7

Log files attached, same error as with audio switcher: 
[logs.zip](https://github.com/fredemmott/StreamDeck-AudioMute/files/3269468/logs.zip)

**Comment by fredemmott** [comment]
Will try to take a look soon -  I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
I can't see a similar issue, and this has generally been working fine for me for the last few years.

If you're still having this, or remember what it's about, please re-open and comment with:
- what behavior you're seeing that you don't expect (if any)
- what behavior you expect that you're not seeing (if any)

The problem in AudioSwitcher was that I was not checking the button's action - toggle or set. This plugin only has a single action - toggle - so is not the same kind of problem.
