### ISSUE TITLE
Issue: Audio Mute buttons lose all functionality upon close and reopen of Stream Deck

### ISSUE THREAD

**Issue by polyh3dron** [fredemmott/StreamDeck-AudioMute#80]
After a relaunch of Stream Deck 6.4.1.19697 with Audio Mute plugin installed, Audio Mute plugin loses ability to select audio devices in Windows. Workaround is to uninstall Audio Mute plugin and reinstall, but this issue will return after the next close and reopen of Stream Deck.

https://i.imgur.com/PJerYDN.png

**Comment by fredemmott** [comment]
Sorry, I don’t have any way to reproduce or investigate this.
